### ISSUE TITLE
Error when opening Firered Rom

### ISSUE THREAD

**Issue by StJobertus** [G3HS/Secret-Tool#12]
Every time I try to download a Firered Rom, i get the Error wich you can see below.
I tried multiple times, and when I open other Roms (like Emerald for Example), it shows no Error.
I have also tried to download the Firered Rom again and tried with a completely new one, and I
have also deleted the Pokeroms.ini file and put a new one in the directory.
I also get the Error when I try to open a Firered Rom wich is patched with MrDS Decap Rombase.

![gen iii hacking suite pokemon firered e c__users_test_desktop_pokemon gba sdk_roms_roms_pokemon - fire red version u gba 17 01 2016 19_06_58](https://cloud.githubusercontent.com/assets/16746789/12396847/e86a72e0-be09-11e5-94dc-ce5f8ded97c5.png)

**Comment by vitor251093** [comment]
That error only happens with 1.1 ROMs. Search again on Google and you may find a ROM of the original version. That one is going to work properly. I don't think I can post any link for that. Sorry :/

**Comment by StJobertus** [comment]
Thanks, that fixed it!
